AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Deploy PostgreSQL instance in private subnets
Parameters:
  EnvironmentName:
    Type: String
  DBName:
    Type: String
  DBUser:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
  DBPort:
    Type: Number
  VpcId:
    Type: String
  PrivateSubnet1Id:
    Type: String
  PrivateSubnet2Id:
    Type: String
  EksSecurityGroupId:
    Type: String
Resources:
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Access to PostgreSQL
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref DBPort
          ToPort: !Ref DBPort
          SourceSecurityGroupId: !Ref EksSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-rds-sg'
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for RDS DB
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      DBSubnetGroupName: !Sub '${EnvironmentName}-db-subnet-group'
  PostgresDB:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      DBName: !Ref DBName
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      Port: !Ref DBPort
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: false
      PubliclyAccessible: false
Outputs:
  RDSInstance:
    Value: !GetAtt PostgresDB.Endpoint.Address
