AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Create S3 bucket for the platform
Parameters:
  S3BucketName:
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
Outputs:
  S3Bucket:
    Value: !Ref S3Bucket
